### ISSUE TITLE
Cody DeployToken.ts

### ISSUE THREAD

**Issue by mivgubel** [mivgubel/Solidity-Bootcamp-Week-3-Project#4]
I've been reviewing your code from week 1 and week 2, 
You did a great job in your scripts from week 1, Congrats!!

I have a comment for the script Deploytoken.ts from week 2, it seems that the function to convert a string to a bytes32 is not used in the script, so maybe you can delete it.

![image](https://user-images.githubusercontent.com/51422943/178156606-7b454d44-467b-40be-9ed5-b2c5585f0e87.png)

Everything else seems great in the script!

**Comment by TechnoGecko** [comment]
Thank you! I will do that

**Comment by TechnoGecko** [comment]
Took out the unnecessary logic, will be included once my pull request is merged
